# Generated by Django 4.1.3 on 2022-11-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/shopnow/')),
            ],
            options={
                'verbose_name': ('Basic view',),
                'verbose_name_plural': ('Basic views',),
            },
        ),
    ]
