# Generated by Django 4.1.3 on 2022-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Featured',
                'verbose_name_plural': 'Featured',
            },
        ),
        migrations.AlterModelOptions(
            name='shopnow',
            options={'verbose_name': 'Basic view', 'verbose_name_plural': 'Basic views'},
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='categories',
            field=models.CharField(choices=[('Fashionable Dress', 'Fashionable Dress'), ('Reasonable Price', 'Reasonable Price')], max_length=50),
        ),
    ]
