# Generated by Django 4.1.3 on 2022-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_featured_alter_shopnow_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Categories/')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Categori',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
