# Generated by Django 4.1.3 on 2022-11-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_categorie_delete_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
