# Generated by Django 4.1.3 on 2022-11-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_vendors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendorr',
        ),
    ]
