# Generated by Django 4.1.3 on 2022-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_vendors_vendorr'),
    ]

    operations = [
        migrations.CreateModel(
            name='fayzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('yoshi', models.IntegerField()),
                ('oqishi', models.TextField()),
                ('image', models.ImageField(upload_to='media/fayzi/')),
            ],
            options={
                'verbose_name': 'Fayzi',
            },
        ),
    ]
