# Generated by Django 4.1.3 on 2022-11-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_fayzi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fayzi',
            options={'verbose_name': 'Fayzi', 'verbose_name_plural': 'Fayzullo'},
        ),
    ]
