# Generated by Django 4.1.3 on 2022-11-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_fayzi_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fayzi',
        ),
    ]
