# Generated by Django 4.1.3 on 2022-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_link_delete_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/Shopproduct/')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('cost_delate', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Shop Product',
                'verbose_name_plural': 'Shop Products',
            },
        ),
        migrations.AlterField(
            model_name='arrived',
            name='image',
            field=models.ImageField(upload_to='media/Arrived/'),
        ),
    ]
